[project]
name = "nn_jax"
version = "0.2.0"
description = "Neural network from scratch using JAX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda13]>=0.8.0",
    "matplotlib>=3.10.8",
    "tqdm>=4.70.0",
]

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "nn_jax"
module-root = "src"

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

[tool.ruff.format]
docstring-code-format = true

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pyrefly>=1.2.0",
    "pytest>=8.3.3",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.5",
]
examples = [
    "huggingface-hub>=1.29.0",
    "pillow>=12.3.0",
    "pyarrow>=25.0.1",
    "seaborn>=0.13.2",
]

[tool.pyrefly]
preset = "basic"
search-path = [
    "scripts/examples/",
]
